### ISSUE TITLE
Deprecated package

### ISSUE THREAD

**Issue by leyenda** [Glavin001/atom-gitter#36]
Greetings gentlemen,

Atom Version: 0.207.0
System: Windows 8 x64
Thrown From: gitter package, v0.6.2

![Deprecated package](https://cloud.githubusercontent.com/assets/394050/8026646/5fea7440-0d44-11e5-8990-24b7f24fd34a.png)

**Comment by Glavin001** [comment]
I am no longer maintaining Atom Gitter. I would be open to reviewing a pull request to fix these deprecation warnings.
